In [1]:
import os

import pandas as pd
import numpy as np

In [2]:
DATA_DIR ='data'
ALARMS_FILE_NAME = 'alarms_clean.csv'
WEATHER_FILE_NAME = 'weather_clean.csv'

Alarms

In [3]:
alarms_path = os.path.join(DATA_DIR, ALARMS_FILE_NAME)

In [4]:
alarms_df = pd.read_csv(alarms_path)

In [5]:
alarms_df["region_city"].unique()

array(['Чернігівська обл.', 'Вінницька обл.', 'Харківська обл.',
       'Тернопільська обл.', 'Київ', 'Рівненська обл.', 'Черкаська обл.',
       'Одеська обл.', 'Запорізька обл.', 'Волинська обл.',
       'Житомирська обл.', 'Херсонська обл.', 'Миколаївська обл.',
       'Хмельницька обл.', 'Івано-Франківська обл.',
       'Дніпропетровська обл.', 'Кіровоградська обл.', 'Полтавська обл.',
       'Київська обл.', 'Сумська обл.', 'Донецька обл.',
       'Закарпатська обл.'], dtype=object)

Weather

In [6]:
weather_path = os.path.join(DATA_DIR, WEATHER_FILE_NAME)

In [7]:
weather_df = pd.read_csv(weather_path)

In [8]:
weather_df["city_address"].unique()

array(['Cherkasy', 'Chernihiv', 'Chernivtsi', 'Dnipro', 'Donetsk',
       'Ivano-Frankivsk', 'Kharkiv', 'Kherson', 'Khmelnytskyi',
       'Kropyvnytskyi', 'Kyiv', 'Lutsk', 'Lviv', 'Mykolaiv', 'Odesa',
       'Poltava', 'Rivne', 'Sumy', 'Ternopil', 'Uzhgorod', 'Vinnytsia',
       'Zaporozhye', 'Zhytomyr'], dtype=object)

In [9]:
weather_kyiv_oblast = weather_df.replace({"Kyiv": "Kyiv oblast"}, inplace=False)
weather_kyiv_oblast = weather_kyiv_oblast[weather_kyiv_oblast["city_address"] == "Kyiv oblast"]

In [10]:
weather_kyiv_oblast

,Unnamed: 0,day_datetime,hour_datetime,city_address,hour_temp,hour_windspeed,hour_winddir,hour_precip,hour_humidity,hour_pressure,hour_cloudcover
10,10,2022-02-24,00:00:00,Kyiv oblast,1.9,7.4,217.0,0.0,93.08,1017.9,99.3
33,33,2022-02-24,01:00:00,Kyiv oblast,2.0,7.2,219.0,0.0,93.09,1018.0,99.7
56,56,2022-02-24,02:00:00,Kyiv oblast,2.0,3.9,212.0,0.0,99.15,1018.1,99.7
79,79,2022-02-24,03:00:00,Kyiv oblast,1.9,4.0,205.0,0.0,99.58,1018.9,97.8
102,102,2022-02-24,04:00:00,Kyiv oblast,1.9,4.0,228.0,0.0,99.78,1019.0,98.7
...,...,...,...,...,...,...,...,...,...,...,...
608199,608199,2025-03-01,19:00:00,Kyiv oblast,-0.1,10.1,181.6,0.0,97.13,1027.0,95.6
608222,608222,2025-03-01,20:00:00,Kyiv oblast,-0.3,0.0,189.9,0.4,92.96,1027.0,100.0
608245,608245,2025-03-01,21:00:00,Kyiv oblast,0.0,9.4,198.3,0.0,96.43,1027.0,100.0
608268,608268,2025-03-01,22:00:00,Kyiv oblast,0.0,8.3,199.9,0.0,97.84,1027.0,97.6
608291,608291,2025-03-01,23:00:00,Kyiv oblast,-0.3,0.0,199.5,0.0,94.33,1026.4,96.4

In [11]:
weather_fixed_df = pd.concat([weather_df, weather_kyiv_oblast])

In [12]:
weather_fixed_df

,Unnamed: 0,day_datetime,hour_datetime,city_address,hour_temp,hour_windspeed,hour_winddir,hour_precip,hour_humidity,hour_pressure,hour_cloudcover
0,0,2022-02-24,00:00:00,Cherkasy,0.9,4.0,132.0,0.0,75.73,1020.0,89.0
1,1,2022-02-24,00:00:00,Chernihiv,0.6,7.2,181.5,0.1,76.81,1019.0,98.5
2,2,2022-02-24,00:00:00,Chernivtsi,2.5,14.4,297.0,0.0,79.03,1023.3,30.0
3,3,2022-02-24,00:00:00,Dnipro,2.0,10.8,4.0,0.0,80.51,1019.0,14.1
4,4,2022-02-24,00:00:00,Donetsk,3.7,4.7,332.7,0.0,74.03,1020.0,95.7
...,...,...,...,...,...,...,...,...,...,...,...
608199,608199,2025-03-01,19:00:00,Kyiv oblast,-0.1,10.1,181.6,0.0,97.13,1027.0,95.6
608222,608222,2025-03-01,20:00:00,Kyiv oblast,-0.3,0.0,189.9,0.4,92.96,1027.0,100.0
608245,608245,2025-03-01,21:00:00,Kyiv oblast,0.0,9.4,198.3,0.0,96.43,1027.0,100.0
608268,608268,2025-03-01,22:00:00,Kyiv oblast,0.0,8.3,199.9,0.0,97.84,1027.0,97.6
608291,608291,2025-03-01,23:00:00,Kyiv oblast,-0.3,0.0,199.5,0.0,94.33,1026.4,96.4